apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: sit737-prac07
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: docker-network-app1
          image: lgcollins/docker-network-app1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
