apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: sit737-prac07
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
