apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: sit737-prac07
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer